#ifndef __SMARTLAMP_CONSTANTS__
#define __SMARTLAMP_CONSTANTS__

// OPERATION CODES TO COMMUNICATE BETWEEN ARDUINO AND BEAGLEBONE BLACK.
#define NO_OP 0x00
#define GET_INTENSITY 0x01
#define SET_INTENSITY 0x02

// PIN CONFIGURATION
#define RX 0
#define TX 1
#define LIGHT_1 3
#define LIGHT_2 5
#define LIGHT_3 6
#define LIGHT_4 9

// DISPLAY CONFIGURATION
#define LCD_COLS 16
#define LCD_ROWS 2

// KEYPAD CONFIGURATION
#define KEYPAD_ROWS 4
#define KEYPAD_COLS 3

#endif // __SMARTLAMP_CONSTANTS__
